<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<AssemblyName>HyperRoles</AssemblyName>
		<Product>My first plugin</Product>
		<Version>1.0.0</Version>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json;
			https://nuget.bepinex.dev/v3/index.json
		</RestoreAdditionalProjectSources>
		<RootNamespace>HyperRoles</RootNamespace>
		<AmongUs>C:\Program Files (x86)\Steam\steamapps\common\Among Us HyR</AmongUs>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
		<PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="$(AmongUs)\BepInEx\core\*.dll" />
		<Reference Include="$(AmongUs)\BepInEx\interop\*.dll" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Modules\" />
	  <Folder Include="Patches\" />
	</ItemGroup>

	<Target Name="Copy" AfterTargets="Build" Condition="'$(AmongUs)' != ''">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(AmongUs)\BepInEx\plugins\" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="Pre\" />
	</Target>

</Project>